### ISSUE TITLE
Suggestions and improvements for ease-to-use

### ISSUE THREAD

**Issue by ajanhallinta** [mathias4833/botw_chest_manager#1]
I'm fairly new to BoTW modding so I might miss some details/reasons, but after quick use of the tool I thought about some improvements:

- **Add "Get map region from save file" button that is always active**. Basically same functionality as in "Get location from save file" button, when the region is different than currently selected. Because I don't usually know the region I'm in at the savefile, so first I have to select dummy map randomly and create new (dummy) chest to enable "Get location from save file" button, then use that to get the actual map region and delete the previous dummy map.

- **Update chest rotation preview automatically when the value is changed**. Now I have to save and switch between objects to update the chest rotation preview.

- **Add option to generate BCML mod folder(s) + rules.txt in tool by given values**. To be honest this might be unnecessary feature and out of scope for this project, although it would be cool to save some precious seconds for simple chest mods.

**Comment by mathias4833** [comment]
Thanks for your feedback! I will soon realease a new version of the tool with these changes.
